package com.rachid_abbad.galleryimage.activities;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.view.MotionEvent;
import android.widget.Toast;

import com.rachid_abbad.galleryimage.R;
import com.rachid_abbad.galleryimage.adapters.GalleryAdapter;
import com.rachid_abbad.galleryimage.models.Image;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    RecyclerView rv;
    GalleryAdapter adapter;
    List<Image> listImages;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        rv = findViewById(R.id.rv);
        listImages = new ArrayList<Image>();
        fillList(listImages);
        adapter = new GalleryAdapter(this, R.layout.custom_layout, listImages);

        rv.setLayoutManager(new GridLayoutManager(this,3));
        rv.setAdapter(adapter);
    }

    private void fillList(List<Image> listImages){
        listImages.add(new Image("Machu Picchu, Peru","machu_picchu_peru","Located high in the Andes mountains of Peru, Machu Picchu is now believed to have been a sacred royal retreat for the Incan rulers. Built in the 15th century AD and abandoned less than a 100 years later, the remote site continues to amaze with its perfectly joined, mortarless, intricate stonework. Huge multi-ton blocks of stone are perfectly joined with each other, without the use of mortar or cement.\n" + "\n" + "The journey to Machu Picchu typically starts in the mountain city of Cusco, which was the capital city of the Inca Empire. Cusco is a fascinating place to explore-be sure to spend a few days there before or after your Machu Picchu adventure."));
        listImages.add(new Image("The Grand Canyon, Arizona","grand_canyon_arizona","This incredible sight, one of the seven natural wonders of the world, is in the U.S. state of Arizona. It's one of those beautiful places for which photos or video just don't do it justice-its sheer size and scope is hard to comprehend.\n" + "\n" + "With geology formed over the past two billion years, yes billion, the 277 mile-long canyon itself is believed to have been started around five to six million years ago. It was formed by the flow of the Colorado River, which still flows through it and continues to erode the geology along its course. The Grand Canyon is up to 18 miles wide in places and up to a mile deep. Imagine standing on the edge, looking down a sheer rock wall almost a mile to the river below."));
        listImages.add(new Image("Rome, Italy","rome_italy","The Eternal City is more like a giant, living museum. Visitors are immersed in and surrounded by thousands of years of history. It's a relatively compact city, and a three-day itinerary gets you to the minimum number of must-see places.\n" + "\n" + "These must-see sites for any visitor include the Colosseum and adjacent Roman Forum; the Pantheon; and Vatican City, a separate country in the middle of central Rome.\n" + "\n" + "Take some time to explore the outskirts of Rome, too. Consider a hike along a tomb-lined section of the Appian Way, the ancient Roman superhighway, and a visit to one of the aqueduct ruins outside the city."));
        listImages.add(new Image("Maui, Hawaii","maui_hawaii","This Hawaiian island offers a wide range of experiences for visitors. You can surf, enjoy a meal on the beach at a five-star luxury resort in Wailea, ride a horse across a dormant volcano in Haleakala National Park, or hike through a rainforest in the West Maui Mountains. The natural scenery is amazing-it's truly one of the most beautiful islands in the world.\n" + "\n" + "When it comes to accommodation, there is something for everyone here, from rustic hippie bungalow bed and breakfasts to five-star luxury resort hotels. Wailea has all the luxury resorts-it's like the beachfront Beverly Hills of Maui. If you're staying here, be sure to venture out and spend some time in Kihei, where the locals hang out."));
        listImages.add(new Image("Masai Mara, Kenya","masai_mara_kenya","Kenya's Masai Mara is an incredible bio-diverse area and a popular safari destination. It's an opportunity to see the \"big five\" animals (lion, leopard, rhinoceros, elephant, and Cape buffalo) all during one trip or, if you're lucky, during one afternoon.\n" + "\n" + "The protected Masai Mara National Reserve park area is huge, over 1,500 square kilometers of mainly grassland, extending all the way to the Serengeti plain of Tanzania. The popular times to visit are during the twice-yearly migrations, the main one being in July and August. Over a million wildebeest and other animals cross the area in huge groups to go from one feeding area to another. Most visitors fly into Nairobi, then take a small bush plane to the Mara."));
        listImages.add(new Image("New Zealand","new_zealand","With its striking natural beauty, friendly citizens, and recent popularity due to its use as the filming location for the Lord of the Rings films (as well as many others), this island nation is one of the world's great places to visit. The biodiversity here is amazing-it's believed New Zealand was one of the last places on earth to have human inhabitants.\n" + "\n" + "Start your visit off in the capital city of Auckland, with its culture, history, and museums. Spend some time on the water and at the beach-Waitemata Harbour has beaches, along with a range of sailing and boating activities."));
        listImages.add(new Image("Istanbul, Turkey","istanbul_turkey","Turkey's capital city is another destination that offers a great mix of culture, food, and history. There are thousands of years of history here, starting with Ancient Greeks and Ancient Romans and leading up through the Ottoman Empire.\n" + "\n" + "There's a mix of the new and the timeless here unlike anywhere else. You can spend the day shopping and the night at a wonderful restaurant eating great Turkish food and dancing to Turkish music, then rise (very early) in the morning to the sound of the Ezan or morning Islamic call to prayer. It echoes across the rooftops as it's broadcast from loudspeakers set atop the minarets of the city's mosques."));
        listImages.add(new Image("Angkor Wat, Cambodia","angkor_wat_cambodia","Located just outside the Cambodian city of Siem Reap, Angkor Wat is the largest religious site in the world. It was created originally as a Hindu temple and mausoleum for the Khmer ruler in the early part of the 12th century and was converted to a Buddhist temple at the end of the 12th century. Just part of a enormous ancient city. Angkor Wat is the temple area, Angor Thom was the city and palace area. There are hundreds of other ruin sites in the area, all part of the ancient capital of Angkor.\n" + "\n" + "Siem Reap and its temples and ruins are now very easily accessible via daily flights from Hong Kong and other large Asian cities. Accommodations range from inexpensive guesthouses to lavish luxury resorts, with everything in between."));
        listImages.add(new Image("London, England","london_england","This historic English city is another destination just filled with incredible places to visit. A trip to London is an opportunity to visit iconic places like the Tower Bridge, Buckingham Palace, and the Tower of London.\n" + "\n" + "Take advantage of the city being a cultural center as well by seeing a West End theater show or watching a musical performance at the Royal Albert Hall. Modern London is also a city of fine dining, luxury hotels, and world-class shopping."));
        listImages.add(new Image("Manhattan, New York","manhattan_newyork","One of the five boroughs of New York City, Manhattan is actually an island, bordered by the East River and the Hudson (and a little bit by the Harlem River). This island is a bit less than 23 square miles and is home to almost two million residents. Add in the daily influx of workers, and the island routinely holds close to four million people.\\n\" + \"No other city in the world offers the frenetic energy of New York City. It's filled with the world's best shopping and dining, along with incredible museums."));
        listImages.add(new Image("Paris, France","paris_france","No visit to the French capital is complete without a trip to and a trip up its most iconic structure. The 300-meter-tall Eiffel Tower was quite simply, the tallest man-made structure in the world, from its opening in 1889 for 41 years until 1930.\n" + "\n" + "Use your visit as a stair workout and climb the 300 steps from ground level to the first of three levels on the tower. If you're in great shape, climb another 300 steps to the second level. Then hop on the elevator here to get to the top. Aside from the workout, you'll also skip most of the crowd who want to take the elevator the whole way."));
        listImages.add(new Image("Montreal, Canada","montrial_canada","As you listen to the sound of French being spoken around you and explore Old Montreal, wandering down its narrow cobblestone streets-you might think you're in France. The historic area is filled with quaint shops and cafés; this Canadian city can be a chance to experience a bit of Europe in North America.\n" + "\n" + "The city also has a thriving food scene, with several popular farmers markets, including the Atwater Market and the Jean Talon Market. It's also known for its bagels, cooked hot and fresh by several iconic must-visit bakeries."));
        listImages.add(new Image("San Francisco, California","san_francisco","San Francisco is a truly unique American city and one of the world's great vacation spots. Explore its hills, ride the cable cars that climb them, and eat some seafood at Fisherman's Wharf. Also spend some time exploring Marin County on the other side of the Golden Gate Bridge, including the picturesque town of Sausalito. The giant redwoods of Muir Woods National Monument are only 30 minutes away and also well worth a side trip.\n" + "\n" +"Be sure to also make time for a visit to or even better, a drive across, the Golden Gate Bridge. This monument to modern engineering genius spans the strait that connects San Francisco Bay and the Pacific Ocean. The almost two-mile-long, six-lane bridge connects the Northern California city with Marin County."));
        listImages.add(new Image("Hong Kong","hong_kong","Asia's largest city can feel like an Asian Manhattan, with giant skyscrapers in a compact area and a serious focus on business. But venture deeper, and you'll find the city's unique mix of ancient Chinese culture and remnants of its British Colonial history as well. Gleaming skyscrapers are built with hand-assembled bamboo scaffolding in a fusion of new and old.\n" + "\n" + "The city is divided into two main sections: Hong Kong Island and Kowloon, separated by Victoria Harbour. Take the Star Ferry across the harbor, still one of the great travel bargains, given the spectacular scenery on both sides. You can also venture into the more rural areas to discover the sparsely populated Outlying Islands, hiking trails, and beautiful beaches."));
        listImages.add(new Image("Marrakesh, Morocco","marrakesh","Start your Marrakech adventure in the Jemaa el-Fnaa, the main, open square in the Moroccan city. It's the gateway to the medina or old walled city. The square is like nowhere else in the world, presenting a constant show of humanity. There are musical performers, snake charmers, monkey trainers, amateur boxing matches, and transvestite belly dancers.\n" + "\n" + "It's also a giant food market, as well as a giant antiques market and swap meet. You can even get a haircut or have some dental work performed. At night, there are fire performers, and an outdoor food fair is set up in the center, with rows of food stalls fronted by counters lined with chairs."));
        listImages.add(new Image("Cartagena, Columbia","cartagena","Colorful Cartagena, one of the great historical Spanish cities of the Caribbean, pulses with life along the north coast of Colombia. Founded in 1533, its old walled city has seen its fortunes rise and fall through the centuries and has more recently experienced a resurgence and revitalization.\n" + "\n" + "Significant restoration of the old city has resulted in once dilapidated 16th-century buildings springing back to life as modern, yet historical hotels, world-class restaurants, and shops. Wander through the narrow city streets to see an impressive church, an open plaza with public works of art, or an eclectic shop selling that perfect souvenir."));
        listImages.add(new Image("Sedona, Arizona","sedona","Surrounded by stunning red rock mountains and buttes, Sedona has one of the most beautiful settings in Arizona. About a 1.5-hour drive north of Phoenix, Sedona is a popular day trip from Phoenix, but the town is worthy of much more than just a few hours.\n" + "\n" + "The drive into Sedona from the south, beginning at the Village of Oak Creek, is stunning and pullouts along the way allow you to stop and enjoy the scenery.\n" + "\n" + "Sedona's main street (89A) is full of interesting tourist shops, art galleries, and restaurants and is an easy place to spend an afternoon. The town is also one of the best places to visit in Arizona if you're looking for great hiking trails and mountain biking trails. You can also find a number of good golf courses and golf resorts in Sedona. If you want something a little more relaxing, consider a stay at one of Sedona's spa resorts."));
        listImages.add(new Image("Hoover Dam, California","hoover_dam","Hoover Dam is one of America's great engineering marvels. This massive structure, completed in 1935, crosses the Colorado River, linking Arizona and Nevada. It is 726 feet high and 1,244 feet long.\n" + "\n" + "Lake Mead, held back by the Hoover Dam, is the largest artificial lake in the United States. It is 110 miles long, and holds the equivalent of two years of flow of the Colorado River.\n" + "\n" + "You can drive or walk across the dam for free, although there is a charge for parking. Another option is to take a tour of Hoover Dam or the Powerplant. The visitor center provides information on the dam and tours, and has a café with some basic food options."));

    }
}